# Generated by Django 4.1.2 on 2022-10-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=1)),
                ('gender', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('symptoms', models.CharField(default='', max_length=150)),
                ('diagnosis', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
